- mapstructure_examples_test.go
Adds an example using the existing `squash` tag to pull in embedded struct fields.
Fixes #19.
> Add squash example

- mapstructure.go
- mapstructure_test.go
Trying to decode negative numbers to `uint` types results in overflowed values. Since trying to do this normally will result in an `error`, it stands to reason that this library should do the same. 
I've left the case that if `WeaklyTypedInput` is set, then the status quo remains, but I could definitely see a case for overriding that.
> Don't decode negative numbers to overflowed uints

- mapstructure.go
Right now when using the decodeHook to build custom structs, I have to build a map that will later be decoded. I can't build my struct directly because it will throw the "'%s' expected a map, got '%s'" error.
This commit fixes it by using the struct without any decoding if src and dest types matche
> Use struct directly if type matches

- mapstructure_benchmark_test.go
- mapstructure_examples_test.go
As requested in https://github.com/mitchellh/mapstructure/issues/37#issuecomment-122170211, here's a PR that adds `decodeViaJSON` with a benchmark and a simple test of basic correctness (in the form of a runnable example)
`decodeViaJSON` performs faster with less memory allocations for simple uses, despite performing the task using an indirect approach. Use it as a baseline for comparing performance of `mapstructure.Decode`.
Credit to @sqs and @gbbr for initial idea.
> Add decodeViaJSON, benchmark and example (as a test).

- mapstructure.go
- mapstructure_test.go
This allows decoding `[]map[x]y` to `map[x]y` by flattening the slice automatically in weakly typed mode.
> Decode slice of maps to a single map in weak mode

- mapstructure.go
- mapstructure_test.go
If the user adds a 'squash' tag to a non-struct type, the call to
structType.NumField() will silently fail, the application stops.
Fixed by adding an error if the squashed field's type is not struct.
> [bug-fix] squash: validate type of sqashed fields also

- mapstructure.go
- mapstructure_test.go
In order to prevent the JSON decoder from converting all values to
`float64`, which causes a number of problems, one must set `UseNumber` on
a JSON decoder which tells it to unmarshal as `json.Number` values.
These can then be converted to ints, floats, or used as strings.
However, although setting this value is very common, mapstructure cannot
currently decode from a `map[string]interface{}` containing a
`json.Number` to a struct with those values represented as int or float.
This could be handled as a hook function, but as Go's habit of converting
all JSON numbers into `float64` is so broken that we've had to globally
set `UseNumber` in all JSON decoding in Vault, it seems like this is
potentially a very common need and should be handled natively.
This adds code and test cases to …
> Handle json.Number values.

- mapstructure.go
Decode hooks have no access to decoding field name, and their errors returned. As result, it is very hard to find what is wrong in input.
Solution: wrap decode hook error and add field name
> Verbose decode hook errors

- mapstructure.go
- mapstructure_test.go
This automatically promotes single standalone values to slices/arrays
if the target type is a slice or array. This only happens in weakly
typed mode.
The single value is weakly decoded into the target slice type, meaning
that a string value can decode to an int slice for example.
This enables the following to decode:
```
source := map[string]interface{}{"key": "4"}
var target struct {
Key []int
}
// Decode source to target
// Pseudocode
result == { Key: []int{4} }
```
> Promote single values to slice values for weakly typed input

- decode_hooks.go
- mapstructure.go
- mapstructure_test.go
This fixes all warnings reported by golint for this codebase and an
unnecessary type cast in mapdecode.go.
> Fix golint warnings

- decode_hooks.go
Summary: Was using a fork of this library and noticed that these lines
were not being used (probably leftover from a refactor).
> Remove unused variable from `decode_hooks.go`

- mapstructure.go
Using `*reflect.StructField` as map key results in a data race. I honestly
do not understand why yet and can only reproduce this in the consul
codebase with high concurrency but this patch fixes it.
The same problem also exists in hashicorp/hcl.
https://github.com/hashicorp/hcl/pull/213
> Fix data race in decodeStruct

- README.md
Put the GoDoc badge right at the top, next to the first
heading so that it is visible and easy to visit.
> README: add godoc badge at the top

- mapstructure.go
- mapstructure_test.go
A field of type interface{} pointing to an existing value should respect
the value type and fill in the pointed object instead of reassigning the
field with a map.
Thanks to @EaseWay for the original fix:
https://github.com/easeway/mapstructure/commit/3f04f074b18a58796031f043c5529147fac2c707
This commit updates EaseWay's fix and adds an additional test
(TestNestedTypeInterface). This test fails on 3f04f07 but now succeeds
due to additional improvements made since the fix was submitted.
Fixes issue #46.
> Improve decoding of interface{} fields

- mapstructure.go
- mapstructure_test.go
In weakly mode,`[]byte` can be converted to `string`,but `string` to `[]byte` will be failed. This pull request adds support for  `string`  to `[]byte` conversion.
> Add support string to byte slice

- mapstructure.go
- mapstructure_test.go
This feature adds the ability to decode structs to maps (essentially allowing the converse of the conventional use of this library). I've tried to be as complete in the test cases that I could add. 
One thing this doesn't do (yet) is map structs recursively. I'm not sure if this library should even do that, the containers for those inner structs can't really be supplied elegantly. If this was to be done - and i'd be happy to do it if that's the case, all structs would be initialized and decoded to `map[string]interface{}`. What do you think @mitchellh?
Closes #53
> Feature: Decode structs to maps

- mapstructure.go
- mapstructure_test.go
A common use case for mapstructure seems to be decoding and then ensuring that some minimum subset of keys was present (when parsing configuration where there are no sensible defaults for example).
This PR adds package level functions matching `Decode` and `WeakDecode` which also take a pointer to a `Metadata` structure, in order to reduce the amount of boilerplate consumers need to implement this. It reduces the consumer code from:
``` go
var result Config
var metadata mapstructure.Metadata
decoder, err := mapstructure.NewDecoder(&mapstructure.DecoderConfig{
Metadata: &metadata,
Result: &result,
})
if err != nil {
return nil, err
}
if err := decoder.Decode(hclMap); err != nil {
return nil, err
}
```
to:
``` go
var result Config
var metadata mapstructure.Metadata
if err := …
```
> Add package-level functions for decoding with metadata

- mapstructure.go
- mapstructure_test.go
This introduces struct to struct decoding for decoding similar structs to other similar but differently typed structs. Along the way, this fixes some issues found that are more common with structs but could've affected non-struct decoding as well.
This is particularly useful for close-but-not-quite-the-same structs. Example:
```go
type A struct {
Input string
}
type B struct {
Input *string
}
// Can now convert like this:
mapstructure.Decode(&a, &b)
```
Additional bugs fixed:
* Decoding a pointer like `*[]string` to a non-pointer `[]string` didn't work at all, this is fixed.
* Decoding a non-pointer `[]string` to a pointer `*[]string` should keep the pointer `nil` if the source slice is nil.
* Decoding a map to a map should set the destination map to nil if the source is nil (vs. empty). …
> Struct to struct decoding + bug fixes

- mapstructure.go
- mapstructure_test.go
If input data is nil before decoding, we bail out early, but if decoding
a non-nil value returns a nil value, we continue with the decode method
and return a zero value. As described in #97, this makes it impossible
to return a nil value from a decode hook. This patch checks for nil
inputs before and after decoding.
[Fixes #97]
> Check input for nil before and after decode hook.

- mapstructure.go
- mapstructure_test.go
Add a testcase, which will fail without patch.
Closes: #146
> Fix empty slice not allocated

- mapstructure.go
- mapstructure_test.go
Extending pull request #51 to support `uint` in addition to the `int` and `float` types when decoding from an unmarshalled `json.Number`.
> Support json.Number decoding to uint

- mapstructure.go
- mapstructure_test.go
Track unusable keys in case the value cannot be set. This helps troubleshoot issues in case a struct was unexported. It took me over a hour to find such an issue once, I would like to avoid this in the future.
> Do not delete key from unused map if field value cannot be set

- mapstructure.go
- mapstructure_test.go
The issue I was running into was that for pointer fields in a struct the key was being recorded twice in the `Metadata.Keys` list. There are some cases where `decodePtr` will recurse into another call to `decode` which will add the field. However the outer `decode` call was unconditionally adding the field as well.
The updates in this PR change the behavior to only add the pointer fields name to the list of keys if no recursion was performed.
> Fix an issues where pointers were causing a key to be recorded twice

- mapstructure.go
- mapstructure_examples_test.go
- mapstructure_test.go
Add support to omitempty anotation in order to not add map keys with empty values
> Support to omitempty

- mapstructure.go
This PR addresses in the docs a [potential confusion](https://github.com/mitchellh/mapstructure/issues/182) for beginners in the Go language regarding skipped unexported fields on a target struct.
> Including 'Unexported fields' section to the docs

- mapstructure.go
Splits allocates memory. This burdens the garbage collector.
By using string.Index to parse string you will be more cache
aware and do not create gabbage.
@mitchellh Can you please review and merge if good enough.
> Avoid unnecessary memory allocations in decodeMapFromStruct

- mapstructure.go
- mapstructure_test.go
> Fix squash decoder option to squash only embedded fields

- mapstructure.go
- mapstructure_test.go
This fixes #187. If the value of an interface is not addressable, we
can't decode into it because we can't replace any keys. To work around
this, we copy the value, decode into that, and then replace the full
value.
> If interface value is not addressable, make copy and set

- mapstructure.go
- mapstructure_bugs_test.go
> Ensure that intermediate maps during struct to struct decoding are settable

- mapstructure.go
In a couple of the tight loops in mapstructure.go `fmt.Sprintf` is used to concatenate values, ex:
```go
fmt.Sprintf("%s[%d]", name, i)
```
This is actually slower and requires additional allocations compared to direct string concatenation and strconv:
```go
name + "[" + strconv.Itoa(i) + "]"
```
```shell
$ go test -bench .
goos: darwin
goarch: amd64
BenchmarkDotPlus-12         	34628470	        29.6 ns/op	       0 B/op	       0 allocs/op
BenchmarkDotSprintf-12      	 7306100	       155 ns/op	      64 B/op	       3 allocs/op
BenchmarkIndexPlus-12       	19705131	        57.9 ns/op	       4 B/op	       1 allocs/op
BenchmarkIndexSprintf-12    	 7302392	       170 ns/op	      40 B/op	       3 allocs/op
```
```go
package main_test
import (
"fmt"
"strconv"
"testing"
)
var prefix = "someprefix" …
```
> Replace fmt.Sprintf calls with string concatenation and strconv

- mapstructure.go
- mapstructure_test.go
This fixed #156.
I know the existence of #199, but this PR supports:
- **Correcty** squashing embedded struct pointers while **decoding map from struct**
- **As well as** squashing embedded struct pointers while **decoding struct from map**
> Add support for squashing embedded struct pointers

- mapstructure.go
- mapstructure_examples_test.go
- mapstructure_test.go
In error messages like `'Key' expected type 'float64', got type 'string'` I think it's also useful to append the actual value.
> Print value in error messages

- decode_hooks.go
- decode_hooks_test.go
- mapstructure.go
This commit adds a third hook func type which has access to the `reflect.Value` representations of both the `from` and the `to` objects. This gives all the same power of the existing hook functions (types, kinds, and data can all be retrieved from values), but with the additional benefit of being able to modify the `to` object.
This change is largely backwards compatible. The only change of the public API (other than adding a new hook type) is a change in the signature of `DecodeHookExec`. If that's a sticking point, I think there may be a way around it, but I haven't looked closely at it. 
Exposing the value of `to` opens up some really powerful patterns such as:
- Recursively decoding structs to maps (#166, #124). This PR includes a hook func that does this
- Setting the concrete struct …
> Add a value hook func

- mapstructure.go
Updates the docs for #226, also updates the `DecodeHookFunc` godoc to include the new `DecodeHookFuncValue` option.
> Update godoc about DecodeHooks and squash

- decode_hooks.go
- decode_hooks_test.go
> Ability to use encoding.TextUnmarshaler

- mapstructure.go
- mapstructure_bugs_test.go
- mapstructure_test.go
Fixes #231
This also reverts the test _change_ that was introduced in 231 back to
the original test. This retains the _new tests_ added in 231 to verify
the behavior of 231.
cc @dnephin
> decodeMapFromStruct: Only deref element if we're squashing the struct

- decode_hooks.go
- decode_hooks_test.go
On < v1.3.3, `ComposeDecodeHookFunc()` was safe to use with no args, but since decea915226622f93c74393f562948d16af8a118 (v1.4.1) it can cause a panic due to it accidentally replacing the `input` with an untyped `nil` after the `nil` check on L405 https://github.com/mitchellh/mapstructure/blob/4664f9ee512b4dfa71b501c4960d469c205b2cf1/mapstructure.go#L405
This PR restores the previous behaviour with minimal impact to allow easier upgrades
> Fix possible panic when using ComposeDecodeHookFunc() with no funcs

- mapstructure.go
- mapstructure_test.go
Fixes #89 and #208 in a more dynamic way than https://github.com/mitchellh/mapstructure/pull/81, https://github.com/mitchellh/mapstructure/pull/176 or https://github.com/mitchellh/mapstructure/pull/207. Rather than just supporting a single use-case this also allows any other form of custom name matcher e.g. using https://github.com/iancoleman/strcase to automatically match to snake_case or kebab-case.
For example:
```go
type Target struct {
FooBar string
}
var out Target
config := &DecoderConfig{
Result: &out,
MatchName: func(mapKey, fieldName string) bool {
return strcase.ToCamel(mapKey) == fieldName
},
}
decoder, _ := NewDecoder(config)
decoder.Decode(map[string]interface{}{
"foo_bar": "baz",
})
```
Would result in `out` being:
```go
Target{
FooBar: "baz",
}
```
> Support custom name matchers

- mapstructure.go
- mapstructure_test.go
Close https://github.com/mitchellh/mapstructure/issues/264
I have confirmed the issue is reproduced by 74cdd45
```console
$ go test -race -run Decode_decodeSliceWithArray ./...
--- FAIL: TestDecode_decodeSliceWithArray (0.00s)
--- FAIL: TestDecode_decodeSliceWithArray/input_is_array (0.00s)
panic: reflect: call of reflect.Value.IsNil on array Value [recovered]
panic: reflect: call of reflect.Value.IsNil on array Value
goroutine 20 [running]:
testing.tRunner.func1.2({0x1237e60, 0xc0001b21b0})
/usr/local/Cellar/go/1.17.5/libexec/src/testing/testing.go:1209 +0x36c
testing.tRunner.func1()
/usr/local/Cellar/go/1.17.5/libexec/src/testing/testing.go:1212 +0x3b6
panic({0x1237e60, 0xc0001b21b0})
/usr/local/Cellar/go/1.17.5/libexec/src/runtime/panic.go:1047 +0x266
reflect.Value.IsNil(...) …
```
> fix: panic when Decode's input is array and output is a slice

- mapstructure.go
- mapstructure_test.go
This is to enable us to more easily (safely & predictably) serialize various structs representing [indexes in go-memdb](https://pkg.go.dev/github.com/hashicorp/go-memdb#Indexer), so that these can be displayed in a useful format in a (memdb) UI.
There are of course builtin indexes which wouldn't necessarily need such special decoding mode, but that assumes we gate the UI on a particular version of go-memdb which has these tags added. More importantly there are custom indexes downstream which may not have any tags and this makes decoded map unpredictable and hard to work with.
> DecoderConfig: Introduce `IgnoreUntaggedFields`

- mapstructure.go
- mapstructure_test.go
This fixes an issue where squash would be disabled for struct fields that have the `",squash"` tag if the decoder also has `Squash: true` set in its config.
> Fix squash not working when decoder config option is set and squash struct tags are present

- mapstructure.go
- mapstructure_test.go
This commit extends the DecoderConfig with an option to fail decoding
if there exist fields in the target struct, which haven't been set
during decoding due to a missing, corresponding value in the input map.
Accordingly, the Metadata has been extended with an Unset array to
receive all field names which have not been set during decoding.
> Add ErrorUnset option to DecoderConfig and Unset array to Metddata

- decode_hooks.go
- decode_hooks_test.go
The aim is to be able to compose existing or custom `DecodeHookFuncs` conditionally.
Currently it is possible to chain calls thanks to `ComposeDecodeHookFunc` but execution is aborted in case an error is found. Therefore, `ComposeDecodeHookFunc` can be seen as an `AND` logical operation.
`OrComposeDecodeHookFunc` on the other hand, executes until a function returns a nil error or all functions returned a non-nil-error. It can be seen as a complimentary `OR` logical operation.
One practical use case is to be able to parse dates with different supported layouts : 
``` go
data := FormData{}
config := &mapstructure.DecoderConfig{
DecodeHook: mapstructure.ComposeDecodeHookFunc(
OrComposeDecodeHookFunc(
// Converts input.type === "month"
mapstructure.StringToTimeHookFunc("2006-01"),
// Converts …
```
> add OrComposeDecodeHookFunc function

- mapstructure.go
- mapstructure_bugs_test.go
> Fix empty keyName when decoding struct -> map with omitempty

- mapstructure.go
Allow mapstructure caller to use `errors.Is` and `errors.As` to determine the cause of errors returned by custom decode hooks.
> Wrap decodehook errors when reporting

- mapstructure.go
- mapstructure_test.go
```go
type Test struct {
Attributes []byte `json:"attributes"`
}
type TestReq struct {
Attributes []byte `json:"attributes"`
}
func TestMapping(t *testing.T) {
req := TestReq{Attributes: []byte(`[{"data": "some data"}]`)}
var test Test
test.Attributes = []byte(`[{"a" : "1"}]`)
err := mapstructure.Decode(req, &test)
if err != nil {
panic(err)
}
fmt.Println(string(test.Attributes))
// result will be [{"data": "some data"}]
}
func TestMappingFail(t *testing.T) {
req := TestReq{Attributes: []byte(`[{"data":"some data"}]`)}
var test Test
test.Attributes = []byte(`[{"a":"1111111111111111111111111111111111111111111111"}]`)
err := mapstructure.Decode(req, &test)
if err != nil {
panic(err)
}
fmt.Println(string(test.Attributes))
// result will be [{"data": "some …
```
> slice mapping bug fix

- decode_hooks.go
- decode_hooks_test.go
if reflect.Kind is reflect.String, it doesn't necessary means it's `string` type. It can be string-based type
> prevent panic in TextUnmarshallerHookFunc
